[package]
name = "server"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "mega-downloader"
path = "src/main.rs"

[dependencies]
engine = { path = "../engine" }
sqlx.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
axum = { version = "0.8", features = ["ws"] }
tower-http = { version = "0.6", features = ["cors", "trace", "fs"] }
tokio-util = { version = "0.7", features = ["io", "compat"] }
async_zip = { version = "0.0.17", features = ["tokio"] }
futures-lite = "2"
